---
- name: Create database
  mysql_db:
    name: "{{ grsshopper_database_name }}"
    state: present

- name: Create database user
  mysql_user:
    name: "{{ grsshopper_database_username }}"
    password: "{{ grsshopper_database_password }}"
    priv: '{{ grsshopper_database_name }}.*:ALL'
    state: present
    
- name: Import database
  mysql_db:
    state: import
    name: "{{ grsshopper_database_name }}"
    target: "{{ grsshopper_root_folder }}/cgi-bin/sql/gRSShopper-ple.sql"
