---
- name: Install additional packages and Perl modules
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - libmime-types-perl
      - libmime-lite-tt-html-perl
      - libcgi-session-perl
      - liblingua-en-inflect-perl
      - libjson-perl
      - libjson-xs-perl
      - libnet-facebook-oauth2-perl
      - libxml-opml-perl
      - librest-client-perl
      - libnet-twitter-lite-perl
      - libdigest-sha-perl
      - libemail-stuffer-perl
      - libtext-vcard-perl
      - libnet-oauth-perl
      - libdbd-mysql-perl
      - libgd-perl
      - libapache2-mod-perl2
      - liblocal-lib-perl
      
- name: Create Perl folder 
  file:
    path: /var/www/perl5
    state: directory
    owner: www-data
    group: www-data

# install Perl modules with cpanm
- name: Install Image::Resize module
  cpanm:
    name: Image::Resize

- name: Install Digest::SHA1 module
  cpanm:
    name: Digest::SHA1

- name: Install JSON::Parse module
  cpanm:
    name: JSON::Parse

- name: Install Mastodon::Client module
  cpanm:
    name: Mastodon::Client
